"""
AegisFlow AI - Decision Engine Adapter

Boundary adapter connecting canonical models.TrafficState to Jayasuriya's DecisionEngine,
and returning a canonical models.SignalDecision.
"""

import uuid
import logging
from typing import Optional
from models import TrafficState, SignalDecision, Lane, Priority
from decision_engine import DecisionEngine

logger = logging.getLogger(__name__)


class DecisionEngineAdapter:
    """Translation adapter isolating Jayasuriya's DecisionEngine from canonical models."""

    def __init__(self, engine: Optional[DecisionEngine] = None):
        self.engine = engine or DecisionEngine()

    def decide(self, canonical_state: TrafficState) -> SignalDecision:
        """
        Translates canonical TrafficState to engine input format,
        invokes Jayasuriya's DecisionEngine, and returns canonical SignalDecision.
        """
        # 1. Convert canonical models.TrafficState -> Jayasuriya engine dictionary input
        legacy_input = {
            "timestamp": canonical_state.timestamp,
            "lanes": {
                lane_enum.value: {
                    "vehicle_count": lane_state.vehicle_count,
                    "occupancy": lane_state.occupancy,
                }
                for lane_enum, lane_state in canonical_state.lanes.items()
            },
            "emergency": {
                "detected": canonical_state.emergency.detected,
                "lane": canonical_state.emergency.lane.value if canonical_state.emergency.lane else None,
            },
            "pedestrians": {
                lane_enum.value: lane_state.pedestrian_count
                for lane_enum, lane_state in canonical_state.lanes.items()
            },
        }

        # 2. Invoke existing Decision Engine
        legacy_decision = self.engine.decide(legacy_input)

        # 3. Convert legacy output -> canonical models.SignalDecision
        # Map active_lane string to Lane enum
        lane_str = str(getattr(legacy_decision, "active_lane", "north")).lower()
        try:
            selected_lane = Lane(lane_str)
        except ValueError:
            selected_lane = Lane.NORTH

        # Map priority string to Priority enum
        prio_str = str(getattr(legacy_decision, "priority", "NORMAL")).upper()
        if prio_str == "EMERGENCY":
            priority = Priority.EMERGENCY
        elif prio_str == "HIGH":
            priority = Priority.HIGH
        elif prio_str == "FALLBACK":
            priority = Priority.FALLBACK
        else:
            priority = Priority.NORMAL

        # Extract reasons list
        raw_reasons = getattr(legacy_decision, "reason", [])
        if isinstance(raw_reasons, str):
            reasons = [raw_reasons]
        elif isinstance(raw_reasons, (list, tuple)):
            reasons = [str(r) for r in raw_reasons]
        else:
            reasons = ["Decision generated by adaptive priority engine"]

        # 4. Extract score breakdown from engine
        score_breakdown = None
        if hasattr(self.engine, 'last_scores') and self.engine.last_scores:
            score_breakdown = {}
            for lane_name, (total_score, breakdown) in self.engine.last_scores.items():
                score_breakdown[lane_name] = {
                    "total_score": round(total_score, 4),
                    **{k: round(v, 4) if isinstance(v, float) else v for k, v in breakdown.items()}
                }

        decision_id = f"dec-{uuid.uuid4().hex[:8]}"

        return SignalDecision(
            decision_id=decision_id,
            timestamp=canonical_state.timestamp,
            selected_lane=selected_lane,
            duration=max(1, int(getattr(legacy_decision, "duration", 15))),
            priority=priority,
            reasons=reasons,
            score_breakdown=score_breakdown,
        )

